config/routes.rb
ProjLaunchedIt::Application.routes.draw do

  resources :projects do
    resources :props
    resources :comments
  end

  root :to => 'projects#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :email, :first_name, :last_name, :project_id

  validates_presence_of :body, :email, :first_name, :last_name, :project_id

  validates :email, :format => { :with=>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :codebase_url, :contact_email, :description, :name, :url

  validates_presence_of :codebase_url, :description, :name, :url

  validates :url, :format => { :with => /[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ }
  validates :codebase_url, :format => { :with => /[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ }
  validates :contact_email, :format => { :with=>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, :allow_blank => true

  has_many :comments
  has_many :props
end

app/models/prop.rb
class Prop < ActiveRecord::Base
  attr_accessible :project_id

  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :load_project

  # GET /comments
  # GET /comments.json
  def index
    @comments = @project.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = @project.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = @project.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = @project.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @project.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@project, @comment], notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = @project.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to [@project, @comment], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = @project.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to project_comments_path(@project) }
      format.json { head :no_content }
    end
  end

  private

    def load_project
      @project = Project.find(params[:project_id])
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @prop = @project.props.build
    rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Application Not Found'
    redirect_to projects_path
  end

  def new
    @project = Project.new

  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  before_filter :load_project

  # GET /props
  # GET /props.json
  def index
    @props = @project.props.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @props }
    end
  end

  # GET /props/1
  # GET /props/1.json
  def show
    @prop = @project.props.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prop }
    end
  end

  # GET /props/new
  # GET /props/new.json
  def new
    @prop = @project.props.new
    @project = @props.project

    redirect_to
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prop }
    end
  end

  # GET /props/1/edit
  def edit
    @prop = @project.props.find(params[:id])
  end

  # POST /props
  # POST /props.json
  def create
    @prop = @project.props.new(params[:prop])
    if @prop.save
      redirect_to project_path(@project), notice: 'Prop was successfully created.' 
    end
  end

  # DELETE /props/1
  # DELETE /props/1.json
  def destroy
    @prop = @project.props.find(params[:id])
    @prop.destroy

    respond_to do |format|
      format.html { redirect_to project_props_path(@project) }
      format.json { head :no_content }
    end
  end

  private

    def load_project
      @project = Project.find(params[:project_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/props_helper.rb
module PropsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@project, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', project_comment_path(@project, @comment) %> |
<%= link_to 'Back', project_comments_path(@project) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Body</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.first_name %></td>
    <td><%= comment.last_name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.body %></td>
    <td><%= comment.project_id %></td>
    <td><%= link_to 'Show', project_comment_path(@project, comment) %></td>
    <td><%= link_to 'Edit', edit_project_comment_path(@project, comment) %></td>
    <td><%= link_to 'Destroy', [@project, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_project_comment_path(@project) %>

app/views/comments/new.html.erb
<div class="comments_page">
  <h1>New comment</h1>

  <%= render 'form' %>

  <%= link_to 'Back', project_comments_path(@project) %>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @comment.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @comment.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Project:</b>
  <%= @comment.project_id %>
</p>


<%= link_to 'Edit', edit_project_comment_path(@project, @comment) %> |
<%= link_to 'Back', project_comments_path(@project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Launched It</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="header">
<a href='/'>
<h1> Launched It! </h1>
<h3> Application portfolio </h3>
</a>
</div>
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/shared/_header.html.erb
header

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :codebase_url %><br />
    <%= f.text_field :codebase_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_show_comments.html.erb
<div class="show-comments">
<h5>Comments</h5>

<% @project.comments.each do |comment| %>
  <div>
    <p>
      <%= comment.first_name + ' ' + comment.last_name %>
      <span class='comment-email'>(<%= mail_to(comment.email) %>)</span>
    :
    </p>
    <p><%= comment.body %></p>
  </div>
<% end %>

<br />

<%= link_to 'New Comment', new_project_comment_path(@project) %>
</div>

app/views/projects/_show_props.html.erb
  <%= @project.props.count %>

<%= link_to 'Add a Prop', new_project_prop_path(@project) %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="error"><%= flash[:error] %></p>
      <% @projects.each_slice(2) do |projects| %>

<div class="row-fluid">
    
        <% projects.each do |project| %>
          <div class="span6 project">
            <h3 class="text-center"><%= link_to project.name, project %></h3>
            <p class="proj-url"><%= link_to project.url, "http://#{project.url}" %></p>
            <p class="proj-code"><%= link_to project.codebase_url, "http://#{project.codebase_url}" %></p>
            <div class="text-center">
              <img src="http://placehold.it/600x300">
            </div>
            <div class="content">
              <p class="proj_description"><%= project.description %></p>
            </div>
            <p class="proj_creater_email"><%= mail_to(project.contact_email) %></p>
            <button type="submit" class="btn"><%= link_to 'View Project', project %></button>
          </div>
        <% end %>


</div>
<% end %>


<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class='project_page'>
  <p id="notice"><%= notice %></p>
  <p id="error"><%= flash[:error] %></p>
  <div class="single-project">
    <p class='proj_name'>
    <p>Name:</p>
      <h3>
        <%= @project.name %>
      </h3>
    </p>

  <p>
    <b>Url:</b>
    <%= @project.url %>
  </p>

  <p>
    <b>Codebase url:</b>
    <%= @project.codebase_url %>
  </p>
  <img src="http://placehold.it/600x300">
  <p>
    <b>Description:</b>
    <%= @project.description %>
  </p>

  <p>
    <b>Contact email:</b>
    <%= @project.contact_email %>
  </p>


  <%= pluralize(@project.props.size-1,'Prop') %>
  <%= render 'props/form'%>
  <%= render 'show_comments' %>

  </br>
  </br>
  </br>
</div>
  <%= link_to 'Edit Project', edit_project_path(@project) %> |
  <%= link_to 'Back to all Projects', projects_path %>
</div>

app/views/props/_form.html.erb
<%= form_for([@project, @prop]) do |f| %>
  <div class="actions">
    <%= f.submit "Give Props"%>
  </div>
<% end %>

app/views/props/edit.html.erb
<h1>Editing prop</h1>

<%= render 'form' %>

<%= link_to 'Show', project_prop_path(@project, @prop) %> |
<%= link_to 'Back', project_props_path(@project) %>

app/views/props/index.html.erb
<h1>Listing props</h1>

<table>
  <tr>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @props.each do |prop| %>
  <tr>
    <td><%= prop.project_id %></td>
    <td><%= link_to 'Show', project_prop_path(@project, prop) %></td>
    <td><%= link_to 'Edit', edit_project_prop_path(@project, prop) %></td>
    <td><%= link_to 'Destroy', [@project, prop], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prop', new_project_prop_path(@project) %>

app/views/props/new.html.erb
<h1>New prop</h1>

<%= render 'form' %>

<%= link_to 'Back', project_props_path(@project) %>

app/views/props/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @prop.project_id %>
</p>


<%= link_to 'Edit', edit_project_prop_path(@project, @prop) %> |
<%= link_to 'Back', project_props_path(@project) %>